language: node_js
node_js:
  - 11

services:
  - docker

install:
  - echo "No installations necessasry"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t $DOCKER_USERNAME/user-api .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/user-api
